/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bportal.kernel.service.base;

import com.bportal.kernel.model.AdvPackage;
import com.bportal.kernel.service.AdvPackageService;
import com.bportal.kernel.service.persistence.AdvItemPersistence;
import com.bportal.kernel.service.persistence.AdvPackagePersistence;
import com.bportal.kernel.service.persistence.AdvTemplatePersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the adv package remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.bportal.kernel.service.impl.AdvPackageServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.bportal.kernel.service.impl.AdvPackageServiceImpl
 * @see com.bportal.kernel.service.AdvPackageServiceUtil
 * @generated
 */
public abstract class AdvPackageServiceBaseImpl extends BaseServiceImpl
	implements AdvPackageService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.bportal.kernel.service.AdvPackageServiceUtil} to access the adv package remote service.
	 */

	/**
	 * Returns the adv item local service.
	 *
	 * @return the adv item local service
	 */
	public com.bportal.kernel.service.AdvItemLocalService getAdvItemLocalService() {
		return advItemLocalService;
	}

	/**
	 * Sets the adv item local service.
	 *
	 * @param advItemLocalService the adv item local service
	 */
	public void setAdvItemLocalService(
		com.bportal.kernel.service.AdvItemLocalService advItemLocalService) {
		this.advItemLocalService = advItemLocalService;
	}

	/**
	 * Returns the adv item remote service.
	 *
	 * @return the adv item remote service
	 */
	public com.bportal.kernel.service.AdvItemService getAdvItemService() {
		return advItemService;
	}

	/**
	 * Sets the adv item remote service.
	 *
	 * @param advItemService the adv item remote service
	 */
	public void setAdvItemService(
		com.bportal.kernel.service.AdvItemService advItemService) {
		this.advItemService = advItemService;
	}

	/**
	 * Returns the adv item persistence.
	 *
	 * @return the adv item persistence
	 */
	public AdvItemPersistence getAdvItemPersistence() {
		return advItemPersistence;
	}

	/**
	 * Sets the adv item persistence.
	 *
	 * @param advItemPersistence the adv item persistence
	 */
	public void setAdvItemPersistence(AdvItemPersistence advItemPersistence) {
		this.advItemPersistence = advItemPersistence;
	}

	/**
	 * Returns the adv package local service.
	 *
	 * @return the adv package local service
	 */
	public com.bportal.kernel.service.AdvPackageLocalService getAdvPackageLocalService() {
		return advPackageLocalService;
	}

	/**
	 * Sets the adv package local service.
	 *
	 * @param advPackageLocalService the adv package local service
	 */
	public void setAdvPackageLocalService(
		com.bportal.kernel.service.AdvPackageLocalService advPackageLocalService) {
		this.advPackageLocalService = advPackageLocalService;
	}

	/**
	 * Returns the adv package remote service.
	 *
	 * @return the adv package remote service
	 */
	public AdvPackageService getAdvPackageService() {
		return advPackageService;
	}

	/**
	 * Sets the adv package remote service.
	 *
	 * @param advPackageService the adv package remote service
	 */
	public void setAdvPackageService(AdvPackageService advPackageService) {
		this.advPackageService = advPackageService;
	}

	/**
	 * Returns the adv package persistence.
	 *
	 * @return the adv package persistence
	 */
	public AdvPackagePersistence getAdvPackagePersistence() {
		return advPackagePersistence;
	}

	/**
	 * Sets the adv package persistence.
	 *
	 * @param advPackagePersistence the adv package persistence
	 */
	public void setAdvPackagePersistence(
		AdvPackagePersistence advPackagePersistence) {
		this.advPackagePersistence = advPackagePersistence;
	}

	/**
	 * Returns the adv template local service.
	 *
	 * @return the adv template local service
	 */
	public com.bportal.kernel.service.AdvTemplateLocalService getAdvTemplateLocalService() {
		return advTemplateLocalService;
	}

	/**
	 * Sets the adv template local service.
	 *
	 * @param advTemplateLocalService the adv template local service
	 */
	public void setAdvTemplateLocalService(
		com.bportal.kernel.service.AdvTemplateLocalService advTemplateLocalService) {
		this.advTemplateLocalService = advTemplateLocalService;
	}

	/**
	 * Returns the adv template remote service.
	 *
	 * @return the adv template remote service
	 */
	public com.bportal.kernel.service.AdvTemplateService getAdvTemplateService() {
		return advTemplateService;
	}

	/**
	 * Sets the adv template remote service.
	 *
	 * @param advTemplateService the adv template remote service
	 */
	public void setAdvTemplateService(
		com.bportal.kernel.service.AdvTemplateService advTemplateService) {
		this.advTemplateService = advTemplateService;
	}

	/**
	 * Returns the adv template persistence.
	 *
	 * @return the adv template persistence
	 */
	public AdvTemplatePersistence getAdvTemplatePersistence() {
		return advTemplatePersistence;
	}

	/**
	 * Sets the adv template persistence.
	 *
	 * @param advTemplatePersistence the adv template persistence
	 */
	public void setAdvTemplatePersistence(
		AdvTemplatePersistence advTemplatePersistence) {
		this.advTemplatePersistence = advTemplatePersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService getClassNameService() {
		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {
		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AdvPackageService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AdvPackage.class;
	}

	protected String getModelClassName() {
		return AdvPackage.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = advPackagePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.bportal.kernel.service.AdvItemLocalService.class)
	protected com.bportal.kernel.service.AdvItemLocalService advItemLocalService;
	@BeanReference(type = com.bportal.kernel.service.AdvItemService.class)
	protected com.bportal.kernel.service.AdvItemService advItemService;
	@BeanReference(type = AdvItemPersistence.class)
	protected AdvItemPersistence advItemPersistence;
	@BeanReference(type = com.bportal.kernel.service.AdvPackageLocalService.class)
	protected com.bportal.kernel.service.AdvPackageLocalService advPackageLocalService;
	@BeanReference(type = AdvPackageService.class)
	protected AdvPackageService advPackageService;
	@BeanReference(type = AdvPackagePersistence.class)
	protected AdvPackagePersistence advPackagePersistence;
	@BeanReference(type = com.bportal.kernel.service.AdvTemplateLocalService.class)
	protected com.bportal.kernel.service.AdvTemplateLocalService advTemplateLocalService;
	@BeanReference(type = com.bportal.kernel.service.AdvTemplateService.class)
	protected com.bportal.kernel.service.AdvTemplateService advTemplateService;
	@BeanReference(type = AdvTemplatePersistence.class)
	protected AdvTemplatePersistence advTemplatePersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameService.class)
	protected com.liferay.portal.kernel.service.ClassNameService classNameService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserService.class)
	protected com.liferay.portal.kernel.service.UserService userService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}