/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bportal.kernel.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AdvItem service. Represents a row in the &quot;BPortal_AdvItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.bportal.kernel.model.impl.AdvItemModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.bportal.kernel.model.impl.AdvItemImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AdvItem
 * @see com.bportal.kernel.model.impl.AdvItemImpl
 * @see com.bportal.kernel.model.impl.AdvItemModelImpl
 * @generated
 */
@ProviderType
public interface AdvItemModel extends BaseModel<AdvItem>, GroupedModel,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a adv item model instance should use the {@link AdvItem} interface instead.
	 */

	/**
	 * Returns the primary key of this adv item.
	 *
	 * @return the primary key of this adv item
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this adv item.
	 *
	 * @param primaryKey the primary key of this adv item
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the adv item ID of this adv item.
	 *
	 * @return the adv item ID of this adv item
	 */
	public long getAdvItemId();

	/**
	 * Sets the adv item ID of this adv item.
	 *
	 * @param advItemId the adv item ID of this adv item
	 */
	public void setAdvItemId(long advItemId);

	/**
	 * Returns the group ID of this adv item.
	 *
	 * @return the group ID of this adv item
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this adv item.
	 *
	 * @param groupId the group ID of this adv item
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this adv item.
	 *
	 * @return the company ID of this adv item
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this adv item.
	 *
	 * @param companyId the company ID of this adv item
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this adv item.
	 *
	 * @return the user ID of this adv item
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this adv item.
	 *
	 * @param userId the user ID of this adv item
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this adv item.
	 *
	 * @return the user uuid of this adv item
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this adv item.
	 *
	 * @param userUuid the user uuid of this adv item
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this adv item.
	 *
	 * @return the user name of this adv item
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this adv item.
	 *
	 * @param userName the user name of this adv item
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this adv item.
	 *
	 * @return the create date of this adv item
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this adv item.
	 *
	 * @param createDate the create date of this adv item
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this adv item.
	 *
	 * @return the modified date of this adv item
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this adv item.
	 *
	 * @param modifiedDate the modified date of this adv item
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the adv package ID of this adv item.
	 *
	 * @return the adv package ID of this adv item
	 */
	public long getAdvPackageId();

	/**
	 * Sets the adv package ID of this adv item.
	 *
	 * @param advPackageId the adv package ID of this adv item
	 */
	public void setAdvPackageId(long advPackageId);

	/**
	 * Returns the adv item name of this adv item.
	 *
	 * @return the adv item name of this adv item
	 */
	@AutoEscape
	public String getAdvItemName();

	/**
	 * Sets the adv item name of this adv item.
	 *
	 * @param advItemName the adv item name of this adv item
	 */
	public void setAdvItemName(String advItemName);

	/**
	 * Returns the content of this adv item.
	 *
	 * @return the content of this adv item
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this adv item.
	 *
	 * @param content the content of this adv item
	 */
	public void setContent(String content);

	/**
	 * Returns the target link of this adv item.
	 *
	 * @return the target link of this adv item
	 */
	@AutoEscape
	public String getTargetLink();

	/**
	 * Sets the target link of this adv item.
	 *
	 * @param targetLink the target link of this adv item
	 */
	public void setTargetLink(String targetLink);

	/**
	 * Returns the duaration of this adv item.
	 *
	 * @return the duaration of this adv item
	 */
	public int getDuaration();

	/**
	 * Sets the duaration of this adv item.
	 *
	 * @param duaration the duaration of this adv item
	 */
	public void setDuaration(int duaration);

	/**
	 * Returns the status of this adv item.
	 *
	 * @return the status of this adv item
	 */
	public int getStatus();

	/**
	 * Sets the status of this adv item.
	 *
	 * @param status the status of this adv item
	 */
	public void setStatus(int status);

	/**
	 * Returns the order of this adv item.
	 *
	 * @return the order of this adv item
	 */
	public int getOrder();

	/**
	 * Sets the order of this adv item.
	 *
	 * @param order the order of this adv item
	 */
	public void setOrder(int order);

	/**
	 * Returns the description of this adv item.
	 *
	 * @return the description of this adv item
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this adv item.
	 *
	 * @param description the description of this adv item
	 */
	public void setDescription(String description);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AdvItem advItem);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AdvItem> toCacheModel();

	@Override
	public AdvItem toEscapedModel();

	@Override
	public AdvItem toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}