/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bportal.kernel.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AdvTemplate service. Represents a row in the &quot;BPortal_AdvTemplate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.bportal.kernel.model.impl.AdvTemplateModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.bportal.kernel.model.impl.AdvTemplateImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AdvTemplate
 * @see com.bportal.kernel.model.impl.AdvTemplateImpl
 * @see com.bportal.kernel.model.impl.AdvTemplateModelImpl
 * @generated
 */
@ProviderType
public interface AdvTemplateModel extends BaseModel<AdvTemplate>, GroupedModel,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a adv template model instance should use the {@link AdvTemplate} interface instead.
	 */

	/**
	 * Returns the primary key of this adv template.
	 *
	 * @return the primary key of this adv template
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this adv template.
	 *
	 * @param primaryKey the primary key of this adv template
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the adv template ID of this adv template.
	 *
	 * @return the adv template ID of this adv template
	 */
	public long getAdvTemplateId();

	/**
	 * Sets the adv template ID of this adv template.
	 *
	 * @param advTemplateId the adv template ID of this adv template
	 */
	public void setAdvTemplateId(long advTemplateId);

	/**
	 * Returns the group ID of this adv template.
	 *
	 * @return the group ID of this adv template
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this adv template.
	 *
	 * @param groupId the group ID of this adv template
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this adv template.
	 *
	 * @return the company ID of this adv template
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this adv template.
	 *
	 * @param companyId the company ID of this adv template
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this adv template.
	 *
	 * @return the user ID of this adv template
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this adv template.
	 *
	 * @param userId the user ID of this adv template
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this adv template.
	 *
	 * @return the user uuid of this adv template
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this adv template.
	 *
	 * @param userUuid the user uuid of this adv template
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this adv template.
	 *
	 * @return the user name of this adv template
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this adv template.
	 *
	 * @param userName the user name of this adv template
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this adv template.
	 *
	 * @return the create date of this adv template
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this adv template.
	 *
	 * @param createDate the create date of this adv template
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this adv template.
	 *
	 * @return the modified date of this adv template
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this adv template.
	 *
	 * @param modifiedDate the modified date of this adv template
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the adv template name of this adv template.
	 *
	 * @return the adv template name of this adv template
	 */
	@AutoEscape
	public String getAdvTemplateName();

	/**
	 * Sets the adv template name of this adv template.
	 *
	 * @param advTemplateName the adv template name of this adv template
	 */
	public void setAdvTemplateName(String advTemplateName);

	/**
	 * Returns the content of this adv template.
	 *
	 * @return the content of this adv template
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this adv template.
	 *
	 * @param content the content of this adv template
	 */
	public void setContent(String content);

	/**
	 * Returns the status of this adv template.
	 *
	 * @return the status of this adv template
	 */
	public int getStatus();

	/**
	 * Sets the status of this adv template.
	 *
	 * @param status the status of this adv template
	 */
	public void setStatus(int status);

	/**
	 * Returns the type of this adv template.
	 *
	 * @return the type of this adv template
	 */
	public int getType();

	/**
	 * Sets the type of this adv template.
	 *
	 * @param type the type of this adv template
	 */
	public void setType(int type);

	/**
	 * Returns the description of this adv template.
	 *
	 * @return the description of this adv template
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this adv template.
	 *
	 * @param description the description of this adv template
	 */
	public void setDescription(String description);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AdvTemplate advTemplate);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AdvTemplate> toCacheModel();

	@Override
	public AdvTemplate toEscapedModel();

	@Override
	public AdvTemplate toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}