/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bportal.kernel.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.bportal.kernel.model.AdvTemplate;
import com.bportal.kernel.model.AdvTemplateModel;
import com.bportal.kernel.model.AdvTemplateSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the AdvTemplate service. Represents a row in the &quot;BPortal_AdvTemplate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link AdvTemplateModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AdvTemplateImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AdvTemplateImpl
 * @see AdvTemplate
 * @see AdvTemplateModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class AdvTemplateModelImpl extends BaseModelImpl<AdvTemplate>
	implements AdvTemplateModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a adv template model instance should use the {@link AdvTemplate} interface instead.
	 */
	public static final String TABLE_NAME = "BPortal_AdvTemplate";
	public static final Object[][] TABLE_COLUMNS = {
			{ "advTemplateId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "advTemplateName", Types.VARCHAR },
			{ "content", Types.VARCHAR },
			{ "status", Types.INTEGER },
			{ "type_", Types.INTEGER },
			{ "description", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("advTemplateId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("advTemplateName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("content", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("type_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table BPortal_AdvTemplate (advTemplateId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,advTemplateName VARCHAR(75) null,content VARCHAR(75) null,status INTEGER,type_ INTEGER,description VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table BPortal_AdvTemplate";
	public static final String ORDER_BY_JPQL = " ORDER BY advTemplate.advTemplateId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY BPortal_AdvTemplate.advTemplateId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.bportal.kernel.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.com.bportal.kernel.model.AdvTemplate"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.bportal.kernel.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.com.bportal.kernel.model.AdvTemplate"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.bportal.kernel.service.util.PropsUtil.get(
				"value.object.column.bitmask.enabled.com.bportal.kernel.model.AdvTemplate"),
			true);
	public static final long STATUS_COLUMN_BITMASK = 1L;
	public static final long ADVTEMPLATEID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static AdvTemplate toModel(AdvTemplateSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		AdvTemplate model = new AdvTemplateImpl();

		model.setAdvTemplateId(soapModel.getAdvTemplateId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setAdvTemplateName(soapModel.getAdvTemplateName());
		model.setContent(soapModel.getContent());
		model.setStatus(soapModel.getStatus());
		model.setType(soapModel.getType());
		model.setDescription(soapModel.getDescription());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<AdvTemplate> toModels(AdvTemplateSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<AdvTemplate> models = new ArrayList<AdvTemplate>(soapModels.length);

		for (AdvTemplateSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.bportal.kernel.service.util.PropsUtil.get(
				"lock.expiration.time.com.bportal.kernel.model.AdvTemplate"));

	public AdvTemplateModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _advTemplateId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAdvTemplateId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _advTemplateId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AdvTemplate.class;
	}

	@Override
	public String getModelClassName() {
		return AdvTemplate.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("advTemplateId", getAdvTemplateId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("advTemplateName", getAdvTemplateName());
		attributes.put("content", getContent());
		attributes.put("status", getStatus());
		attributes.put("type", getType());
		attributes.put("description", getDescription());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long advTemplateId = (Long)attributes.get("advTemplateId");

		if (advTemplateId != null) {
			setAdvTemplateId(advTemplateId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String advTemplateName = (String)attributes.get("advTemplateName");

		if (advTemplateName != null) {
			setAdvTemplateName(advTemplateName);
		}

		String content = (String)attributes.get("content");

		if (content != null) {
			setContent(content);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		Integer type = (Integer)attributes.get("type");

		if (type != null) {
			setType(type);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}
	}

	@JSON
	@Override
	public long getAdvTemplateId() {
		return _advTemplateId;
	}

	@Override
	public void setAdvTemplateId(long advTemplateId) {
		_columnBitmask = -1L;

		_advTemplateId = advTemplateId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getAdvTemplateName() {
		if (_advTemplateName == null) {
			return StringPool.BLANK;
		}
		else {
			return _advTemplateName;
		}
	}

	@Override
	public void setAdvTemplateName(String advTemplateName) {
		_advTemplateName = advTemplateName;
	}

	@JSON
	@Override
	public String getContent() {
		if (_content == null) {
			return StringPool.BLANK;
		}
		else {
			return _content;
		}
	}

	@Override
	public void setContent(String content) {
		_content = content;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (!_setOriginalStatus) {
			_setOriginalStatus = true;

			_originalStatus = _status;
		}

		_status = status;
	}

	public int getOriginalStatus() {
		return _originalStatus;
	}

	@JSON
	@Override
	public int getType() {
		return _type;
	}

	@Override
	public void setType(int type) {
		_type = type;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			AdvTemplate.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AdvTemplate toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (AdvTemplate)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AdvTemplateImpl advTemplateImpl = new AdvTemplateImpl();

		advTemplateImpl.setAdvTemplateId(getAdvTemplateId());
		advTemplateImpl.setGroupId(getGroupId());
		advTemplateImpl.setCompanyId(getCompanyId());
		advTemplateImpl.setUserId(getUserId());
		advTemplateImpl.setUserName(getUserName());
		advTemplateImpl.setCreateDate(getCreateDate());
		advTemplateImpl.setModifiedDate(getModifiedDate());
		advTemplateImpl.setAdvTemplateName(getAdvTemplateName());
		advTemplateImpl.setContent(getContent());
		advTemplateImpl.setStatus(getStatus());
		advTemplateImpl.setType(getType());
		advTemplateImpl.setDescription(getDescription());

		advTemplateImpl.resetOriginalValues();

		return advTemplateImpl;
	}

	@Override
	public int compareTo(AdvTemplate advTemplate) {
		int value = 0;

		if (getAdvTemplateId() < advTemplate.getAdvTemplateId()) {
			value = -1;
		}
		else if (getAdvTemplateId() > advTemplate.getAdvTemplateId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof AdvTemplate)) {
			return false;
		}

		AdvTemplate advTemplate = (AdvTemplate)obj;

		long primaryKey = advTemplate.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		AdvTemplateModelImpl advTemplateModelImpl = this;

		advTemplateModelImpl._setModifiedDate = false;

		advTemplateModelImpl._originalStatus = advTemplateModelImpl._status;

		advTemplateModelImpl._setOriginalStatus = false;

		advTemplateModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<AdvTemplate> toCacheModel() {
		AdvTemplateCacheModel advTemplateCacheModel = new AdvTemplateCacheModel();

		advTemplateCacheModel.advTemplateId = getAdvTemplateId();

		advTemplateCacheModel.groupId = getGroupId();

		advTemplateCacheModel.companyId = getCompanyId();

		advTemplateCacheModel.userId = getUserId();

		advTemplateCacheModel.userName = getUserName();

		String userName = advTemplateCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			advTemplateCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			advTemplateCacheModel.createDate = createDate.getTime();
		}
		else {
			advTemplateCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			advTemplateCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			advTemplateCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		advTemplateCacheModel.advTemplateName = getAdvTemplateName();

		String advTemplateName = advTemplateCacheModel.advTemplateName;

		if ((advTemplateName != null) && (advTemplateName.length() == 0)) {
			advTemplateCacheModel.advTemplateName = null;
		}

		advTemplateCacheModel.content = getContent();

		String content = advTemplateCacheModel.content;

		if ((content != null) && (content.length() == 0)) {
			advTemplateCacheModel.content = null;
		}

		advTemplateCacheModel.status = getStatus();

		advTemplateCacheModel.type = getType();

		advTemplateCacheModel.description = getDescription();

		String description = advTemplateCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			advTemplateCacheModel.description = null;
		}

		return advTemplateCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{advTemplateId=");
		sb.append(getAdvTemplateId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", advTemplateName=");
		sb.append(getAdvTemplateName());
		sb.append(", content=");
		sb.append(getContent());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", type=");
		sb.append(getType());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("com.bportal.kernel.model.AdvTemplate");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>advTemplateId</column-name><column-value><![CDATA[");
		sb.append(getAdvTemplateId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>advTemplateName</column-name><column-value><![CDATA[");
		sb.append(getAdvTemplateName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>content</column-name><column-value><![CDATA[");
		sb.append(getContent());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>type</column-name><column-value><![CDATA[");
		sb.append(getType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = AdvTemplate.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			AdvTemplate.class
		};
	private long _advTemplateId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _advTemplateName;
	private String _content;
	private int _status;
	private int _originalStatus;
	private boolean _setOriginalStatus;
	private int _type;
	private String _description;
	private long _columnBitmask;
	private AdvTemplate _escapedModel;
}